#!/usr/bin/env python
# -*- coding:utf-8 -*-
# AUTHOR: Ti Bai
# EMAIL: tibaiw@gmail.com
# AFFILIATION: MAIA Lab | UT Southwestern Medical Center
# DATETIME: 7/20/2020 10:57 PM

from yacs.config import CfgNode as CN

# HIGH_RESOLUTION_NET
HIGH_RESOLUTION_NET = CN()
HIGH_RESOLUTION_NET.NAME = 'HRNET'
HIGH_RESOLUTION_NET.INPUT_CHANNELS = 1
HIGH_RESOLUTION_NET.OUTPUT_CHANNELS = 1
HIGH_RESOLUTION_NET.INPUT_SIZE = (512, 512)
HIGH_RESOLUTION_NET.SHIFT_SIZE = (192, 192)
HIGH_RESOLUTION_NET.NORMALIZATION_TYPE = 'instance'

HIGH_RESOLUTION_NET.EXTRA = CN()
HIGH_RESOLUTION_NET.EXTRA.PRETRAINED_LAYERS = ['*']
HIGH_RESOLUTION_NET.EXTRA.STEM_INPLANES = 64
HIGH_RESOLUTION_NET.EXTRA.FINAL_CONV_KERNEL = 1
HIGH_RESOLUTION_NET.EXTRA.WITH_HEAD = True

HIGH_RESOLUTION_NET.EXTRA.STAGE1 = CN()
HIGH_RESOLUTION_NET.EXTRA.STAGE1.NUM_MODULES = 1
HIGH_RESOLUTION_NET.EXTRA.STAGE1.NUM_BRANCHES = 1
HIGH_RESOLUTION_NET.EXTRA.STAGE1.NUM_BLOCKS = [4]
HIGH_RESOLUTION_NET.EXTRA.STAGE1.NUM_CHANNELS = [32]
HIGH_RESOLUTION_NET.EXTRA.STAGE1.BLOCK = 'BOTTLENECK'
HIGH_RESOLUTION_NET.EXTRA.STAGE1.FUSE_METHOD = 'SUM'

HIGH_RESOLUTION_NET.EXTRA.STAGE2 = CN()
HIGH_RESOLUTION_NET.EXTRA.STAGE2.NUM_MODULES = 1
HIGH_RESOLUTION_NET.EXTRA.STAGE2.NUM_BRANCHES = 2
HIGH_RESOLUTION_NET.EXTRA.STAGE2.NUM_BLOCKS = [4, 4]
HIGH_RESOLUTION_NET.EXTRA.STAGE2.NUM_CHANNELS = [32, 64]
HIGH_RESOLUTION_NET.EXTRA.STAGE2.BLOCK = 'BASIC'
HIGH_RESOLUTION_NET.EXTRA.STAGE2.FUSE_METHOD = 'SUM'

HIGH_RESOLUTION_NET.EXTRA.STAGE3 = CN()
HIGH_RESOLUTION_NET.EXTRA.STAGE3.NUM_MODULES = 1
HIGH_RESOLUTION_NET.EXTRA.STAGE3.NUM_BRANCHES = 3
HIGH_RESOLUTION_NET.EXTRA.STAGE3.NUM_BLOCKS = [4, 4, 4]
HIGH_RESOLUTION_NET.EXTRA.STAGE3.NUM_CHANNELS = [32, 64, 128]
HIGH_RESOLUTION_NET.EXTRA.STAGE3.BLOCK = 'BASIC'
HIGH_RESOLUTION_NET.EXTRA.STAGE3.FUSE_METHOD = 'SUM'

HIGH_RESOLUTION_NET.EXTRA.STAGE4 = CN()
HIGH_RESOLUTION_NET.EXTRA.STAGE4.NUM_MODULES = 1
HIGH_RESOLUTION_NET.EXTRA.STAGE4.NUM_BRANCHES = 4
HIGH_RESOLUTION_NET.EXTRA.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
HIGH_RESOLUTION_NET.EXTRA.STAGE4.NUM_CHANNELS = [32, 64, 128, 256]
HIGH_RESOLUTION_NET.EXTRA.STAGE4.BLOCK = 'BASIC'
HIGH_RESOLUTION_NET.EXTRA.STAGE4.FUSE_METHOD = 'SUM'

# UNET
UNET = CN()
UNET.NAME = 'UNET'
UNET.INPUT_CHANNELS = 1
UNET.OUTPUT_CHANNELS = 1
UNET.DOWNSAMPLING_NUMBER = 8
UNET.DIMENSION = '2d'
UNET.FILTER_NUMBER_LAST_CONV_LAYER = 64
UNET.INPUT_SIZE = (64, 256, 256)
UNET.SHIFT_SIZE = (8, 16, 16)
UNET.NORMALIZATION_TYPE = 'instance'
UNET.INIT_TYPE = 'normal'
UNET.INIT_GAIN = 0.02

# PLAINNET
PLAINNET = CN()
PLAINNET.NAME = 'PLAINNET'
PLAINNET.INPUT_CHANNELS = 1
PLAINNET.OUTPUT_CHANNELS = 1
PLAINNET.LAYER_NUMBER = 8
PLAINNET.CHANNEL_NUMBER = 32
PLAINNET.DIMENSION = '2d'
PLAINNET.INPUT_SIZE = (512, 512)
PLAINNET.SHIFT_SIZE = (192, 192)
PLAINNET.NORMALIZATION_TYPE = 'instance'


GENERATOR_CONFIGS = {
    'HRNET': HIGH_RESOLUTION_NET,
    'UNET': UNET,
    'PLAINNET': PLAINNET
}
