#!/usr/bin/env python
# -*- coding:utf-8 -*-
# AUTHOR: Ti Bai
# EMAIL: tibaiw@gmail.com
# AFFILIATION: MAIA Lab | UT Southwestern Medical Center
# DATETIME: 7/20/2020 10:57 PM

from yacs.config import CfgNode as CN

# M3Net
M3NET = CN()
M3NET.NAME = 'M3NET'
M3NET.INPUT_CHANNELS = (256, 8, 8)
M3NET.FEATURE_CHANNELS = (256, 16, 16)
M3NET.LAYER_NUMBERS = (3, 3, 3)
M3NET.PREDICTION_HEAD_CHANNELS = (256, 32, 32)
M3NET.SCALE_DIMENSION = (2, 3, 3)
M3NET.INPUT_SIZE = (64, 256, 256)
M3NET.SHIFT_SIZE = (8, 16, 16)
M3NET.NORMALIZATION_TYPE = 'batch'
M3NET.INIT_TYPE = 'normal'
M3NET.INIT_GAIN = 0.02

UNET = CN()
UNET.NAME = 'UNET'
UNET.INPUT_CHANNELS = 1
UNET.OUTPUT_CHANNELS = 1
UNET.DOWNSAMPLING_NUMBER = 8
UNET.DIMENSION = '2d'
UNET.FILTER_NUMBER_LAST_CONV_LAYER = 64
UNET.INPUT_SIZE = (64, 256, 256)
UNET.SHIFT_SIZE = (8, 16, 16)
UNET.NORMALIZATION_TYPE = 'instance'
UNET.INIT_TYPE = 'normal'
UNET.INIT_GAIN = 0.02

GENERATOR_CONFIGS = {
    'M3NET': M3NET,
    'UNET': UNET
}
